* embark - Emacs Mini-Buffer Actions Rooted in Keymaps.

This package provides a command =embark-act= to execute actions on
the top minibuffer completion canidate (the one that would be
chosen by minibuffer-force-complete).  You should bind =embark-act=
to some key in =minibuffer-local-completion-map=.

The actions are arranged into keymaps separated by the type of
completion currently taking place.  By default =embark= recognizes
the following types of completion: file names, buffers and symbols.
The classification is configurable, see the variable
=embark-classifiers=.

For any given type there is a corresponding keymap as noted in
=embark-keymap-alist=.  For example, for the completion category
=file=, by default the corresponding keymap is =embark-file-map=.
In this keymap you can bind normal commands you might want to use
on file names.  For example, by default =embark-file-map= binds
=delete-file= to "d", =rename-file= to "r" and =copy-file= to "c".

The default keymaps that come with =embark= all set
=embark-general-map= as their parent, so that the actions bound
there are available no matter what type of completion you are in
the middle of.  By default this includes bindings to save the
current candidate in the kill ring and to insert the current
candidate in the previously selected buffer (the buffer that was
current when you executed a command that opened up the minibuffer).

You can use any command that reads from the minibuffer as an action
and the target of the action will be inserted at the first
minibuffer prompt.  You don't even have to bind a command in one of
the keymaps listed in =embark-keymap-alist= to use it!  After
running =embark-act= all of your keybindings and even
=execute-extended-command= can be used to run a command.

Additionally you can write your own commands that do not read from
the minibuffer but act on the current target anyway: just use the
=embark-target= function (exactly once!: it "self-destructs") to
retrieve the current target.  See the definitions of
=embark-insert= or =embark-save= for examples.

If you wish to see a reminder of which actions are available, for
now, I recommend installing which-key and using =which-key-mode=
with the =which-key-show-transient-maps= variable set to =t=.
